services:
  - type: web
    name: stock-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
